openapi: 3.0.0
x-stoplight:
  id: yt5veuewymbck
info:
  title: ATEB ValidatePO
  version: '1.0'
  description: 'The purpose of the ATEB Validate Purchase Order API is to validate purchase orders for an external application called ATEB.  Valid purchase orders will exist in Eaton ERP systems, Oracle, and SAP. The request message will include Eaton site and purchase order information from the ATEB application. The approach is to find the PO in the appropriate system, and respond back to ATEB.  '
servers:
  - url: 'https ://api-lab.eaton.com/finance/ap/v1'
    description: LAB
  - url: 'https ://api-dev.eaton.com/finance/ap/v1'
    description: DEV
  - url: 'https ://api-sit.eaton.com/finance/ap/v1'
    description: SIT
  - url: 'https ://api-qa.eaton.com/finance/ap/v1'
    description: QA
paths:
  /purchaseorders/validate:
    post:
      summary: ValidatePurchaseOrder
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  invoiceNumber:
                    type: string
                    minLength: 1
                  returnStatus:
                    type: string
                    minLength: 1
                  reasonCode:
                    type: string
                    minLength: 1
                  invoiceLine:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - invoiceLineNumber
                        - returnStatus
                        - reasonCode
                      properties:
                        invoiceLineNumber:
                          type: string
                          minLength: 1
                        returnStatus:
                          type: string
                          minLength: 1
                        reasonCode:
                          type: string
                          minLength: 1
                required:
                  - invoiceNumber
                  - returnStatus
                  - reasonCode
                  - invoiceLine
                x-examples:
                  example-1:
                    invoiceNumber: string
                    returnStatus: string
                    reasonCode: string
                    invoiceLine:
                      - invoiceLineNumber: string
                        returnStatus: string
                        reasonCode: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    x-stoplight:
                      id: ms9ks1frwfaf4
                    items:
                      x-stoplight:
                        id: 22wyyjhhyky1o
                      type: object
                      minProperties: 2
                      maxProperties: -1
                      properties:
                        code:
                          type: string
                          x-stoplight:
                            id: 2kmm8ckbcqpqn
                        message:
                          type: string
                          x-stoplight:
                            id: t2xkczydg6ska
                        status:
                          type: string
                          x-stoplight:
                            id: rt355l2v5h98h
                        dateTime:
                          type: string
                          x-stoplight:
                            id: hmnv3nbelpbva
                        trackingId:
                          type: string
                          x-stoplight:
                            id: 2lkbagqjnyxiw
              examples:
                400Example:
                  value:
                    errors:
                      - code: Internal Server Error
                        message: An internal server error occurred. Please contact Eaton support and refer to tracking number
                        status: 500
                        dateTime: 'Sun, 20 March 2023 15:07:51 UTC'
                        trackingId: ''
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                        message:
                          type: string
                        status:
                          type: number
                        dateTime:
                          type: string
                        trackingId:
                          type: string
              examples:
                '500':
                  value:
                    errors:
                      - code: Internal Server Error
                        message: An internal server error occurred. Please contact Eaton support and refer to tracking number
                        status: 500
                        dateTime: 'Sun, 20 March 2023 15:07:51 UTC'
                        trackingId: ''
      operationId: post-purchaseorders-validate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  purchaseOrder:
                    plantCode: string
                    supplierNumber: string
                    invoiceNumber: string
                  purchaseOrderLine:
                    invoiceLineNumber: string
                    PONumber: string
                    POCurrencyCode: string
                    POLineNumber: string
                    partNumber: string
              properties:
                PurchaseOrder:
                  type: object
                  required:
                    - SupplierNumber
                    - InvoiceNumber
                  x-stoplight:
                    id: mipk0mr0mwiwk
                  properties:
                    PlantCode:
                      type: string
                      minLength: 1
                      x-stoplight:
                        id: gg1syjeudovq9
                    SupplierNumber:
                      type: string
                      minLength: 1
                      x-stoplight:
                        id: 6lsebpuatd6mn
                    InvoiceNumber:
                      type: string
                      minLength: 1
                      x-stoplight:
                        id: ynjhd4b079rao
                PurchaseOrderline:
                  type: object
                  required:
                    - InvoiceLineNumber
                    - PONumber
                    - POCurrencyCode
                    - POLineNumber
                  x-stoplight:
                    id: douwsapwig7ry
                  properties:
                    InvoiceLineNumber:
                      type: string
                      minLength: 1
                      x-stoplight:
                        id: dveheuh75fv55
                    PONumber:
                      type: string
                      minLength: 1
                    POCurrencyCode:
                      type: string
                      minLength: 1
                    POLineNumber:
                      type: string
                      minLength: 1
                    PartNumber:
                      type: string
                      minLength: 1
                      x-stoplight:
                        id: nlqix8o61w546
              required:
                - PurchaseOrder
                - PurchaseOrderline
        description: 'These are the parameters sent to the proxy from ATEB '
      description: ''
      parameters: []
components:
  schemas: {}
  securitySchemes:
    API Key - 1:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://eaton-nonprod-lab.apigee.net/oauth/accesstoken?grant_type=client_credentials'
          refreshUrl: ''
          scopes: {}
      description: ATEB OAuth2.0
